site_name: Minecraft For Dev
theme: 
  name: material
nav: 
  - 홈: index.md
  - 데이터팩: 
    - 홈 : datapack/index.md
    - 리팩토링 :
      - 홈 : datapack/refactor/index.md
      - 마인크래프트 :
        - 틱/로드 : datapack/refactor/element/minecraft/0_tick_and_load.md
        - 최상위 함수 : datapack/refactor/element/minecraft/1_top_function.md
        - 함수 우선순위 : datapack/refactor/element/minecraft/2_function_priority.md
        - 관리부와 실행부 : datapack/refactor/element/minecraft/3_management_execution.md
      - 클린코드 :
        - 단일 책임 : datapack/refactor/element/cleancode/0_single_responsibility.md
        - 이름의 가독성 : datapack/refactor/element/cleancode/1_namespace_readability.md
        - 중복 제거 : datapack/refactor/element/cleancode/2_remove_duplicates.md
        - 주석 : datapack/refactor/element/cleancode/3_annotation.md
    - 스니펫 :
      - 홈 : datapack/snippet/index.md
      - 아이디 : datapack/snippet/element/condition_undefined_number.md
      - 회전 : datapack/snippet/element/rotation.md
  - 프로그램: 
    - 홈 : program/index.md
    - renderdoc :
      - 홈 : program/renderdoc/index.md
      - 설치 : program/renderdoc/element/0_install.md
      - 실행 : program/renderdoc/element/1_play.md
      - 사용 : program/renderdoc/element/2_using.md
  - 리소스팩: 
    - 홈 : resourcepack/index.md
    - 폰트 :
      - 홈 : resourcepack/font/index.md
      - providers : resourcepack/font/element/providers.md
      - bitmap : resourcepack/font/element/bitmap.md
      - ttf : resourcepack/font/element/ttf.md
      - space : resourcepack/font/element/space.md
      - unihex : resourcepack/font/element/unihex.md
      - reference : resourcepack/font/element/reference.md
    - 셰이더 :
      - 홈 : resourcepack/shader/index.md
      - core : resourcepack/shader/element/core.md